changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: ':boom: Breaking Changes'
      labels:
        - Semver-Major
        - breaking
    - title: ':sparkles: Features'
      labels:
        - Semver-Minor
        - feature
    - title: ':technologist: Enhancements'
      labels:
        - Semver-Minor
        - enhancement
    - title: ':bug: Bugfixes'
      labels:
        - Semver-Minor
        - bug
    - title: ':hammer: Other Changes'
      labels:
        - "*"
